In [1]:
import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np


# Filter

In [ ]:
img=cv.imread("C:/Users/SN112/Downloads/elsa.jpg")
kernel=np.ones((3,3),np.float32)/9
filter=cv.filter2D(img,-1,kernel)
cv.imshow('image',img) 
cv.imshow('filter',filter)
cv.waitKey(0)
cv.destroyAllWindows()


# Blur


In [ ]:
img=cv.imread('C:/Users/SN112/Downloads/elsa.jpg')
blur=cv.blur(img,(15,15))
cv.imshow('image',img)
cv.imshow('blur',blur)
cv.waitKey()
cv.destroyAllWindows()

# Gaussian Blur

In [ ]:
img=cv.imread('C:/Users/SN112/Downloads/elsa.jpg')
Gblur=cv.GaussianBlur(img,(55,55),0)
cv.imshow('image',img)
cv.imshow('Gaussian',Gblur)
cv.waitKey()
cv.destroyAllWindows()

In [ ]:
img=cv.imread('C:/Users/SN112/Downloads/temple.jpg')
print(img.shape)
Gblur=cv.GaussianBlur(img,(55,55),0)
cv.imshow('image',img)
cv.imshow('Gaussian',Gblur)
cv.waitKey(0)
cv.destroyAllWindows()

# Bilateral Filter

In [ ]:
img=cv.imread('C:/Users/SN112/Downloads/temple.jpg')
print(img.shape)
bfilter=cv.bilateralFilter(img,7,90,90)
cv.imshow('image',img)
cv.imshow('bilateralFilter',bfilter)
cv.waitKey(0)
cv.destroyAllWindows()

# Median Filters

In [ ]:
img=cv.imread('C:/Users/SN112/Downloads/sn.jpg')
mfilter=cv.medianBlur(img,5)
cv.imshow('imag',img)
cv.imshow('medianBlur',mfilter)
cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
titles=['img','2D','''blur','gaussian','bilateral','median']
images=[img,filter,blur,gblur,bfilter,medianFilter]
cv.waitKey(0)
cv.destroyAllWindows()

# LAPLASIAN FILTER

In [15]:
img = cv.imread('C:/Users/SN112/Downloads/123.jpeg',0)
lap = cv.Laplacian(img,cv.CV_64F,ksize=3)
lap = np.uint8(np.absolute(lap))
cv.imshow('image',img)
cv.imshow('laplacian',lap)
cv.waitKey(0)
cv.destroyAllWindows()



# sobel filter

In [24]:
img=cv.imread('C:/Users/SN112/Downloads/ghost.jfif',0)
soblex=cv.Sobel(img,cv.CV_64F,1,0,ksize=3)
soblex=np.uint8(np.absolute(soblex))
print(soblex)
cv.imshow('image',img)
cv.imshow('soblex',soblex)
cv.waitKey(0)
cv.destroyAllWindows()



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [26]:
sobley=cv.Sobel(img,cv.CV_64F,0,1,ksize=3)
sobley=np.uint8(np.absolute(sobley))
print(soblex)
cv.imshow('image',img)
cv.imshow('sobley',sobley)
cv.waitKey(0)
cv.destroyAllWindows()


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
