In [3]:
import cv2
import numpy as np

In [4]:
im1=cv2.imread("C:/Users/SN112/Downloads/yoyo.jfif")

In [5]:
im1

array([[[ 54, 229, 255],
        [ 54, 229, 255],
        [ 54, 229, 255],
        ...,
        [ 54, 229, 255],
        [ 54, 229, 255],
        [ 54, 229, 255]],

       [[ 54, 229, 255],
        [ 54, 229, 255],
        [ 54, 229, 255],
        ...,
        [ 54, 229, 255],
        [ 54, 229, 255],
        [ 54, 229, 255]],

       [[ 54, 229, 255],
        [ 54, 229, 255],
        [ 54, 229, 255],
        ...,
        [ 54, 229, 255],
        [ 54, 229, 255],
        [ 54, 229, 255]],

       ...,

       [[ 53, 228, 255],
        [ 53, 228, 255],
        [ 53, 228, 255],
        ...,
        [ 53, 228, 255],
        [ 53, 228, 255],
        [ 53, 228, 255]],

       [[ 53, 228, 255],
        [ 53, 228, 255],
        [ 53, 228, 255],
        ...,
        [ 53, 228, 255],
        [ 53, 228, 255],
        [ 53, 228, 255]],

       [[ 53, 228, 255],
        [ 53, 228, 255],
        [ 53, 228, 255],
        ...,
        [ 53, 228, 255],
        [ 53, 228, 255],
        [ 53, 228, 255]]

In [6]:
shp=im1.shape
print(shp)

(736, 736, 3)


In [7]:
height,width=im1.shape[:2]
print(height)
print(width)

736
736


In [8]:
cent=(height/2,width/2)
cent

(368.0, 368.0)

In [9]:
rotation_matrix=cv2.getRotationMatrix2D(center=cent,angle=25,scale=0.5)

In [10]:
print(rotation_matrix)

[[ 4.53153894e-01  2.11309131e-01  1.23477607e+02]
 [-2.11309131e-01  4.53153894e-01  2.79001127e+02]]


In [11]:
rotated_im =cv2.warpAffine(src=im1,M=rotation_matrix ,dsize=(width,height)) 


In [12]:
cv2.imshow('original image',im1)
cv2.waitKey(0)
cv2.imshow('rotated image',rotated_im)
cv2.waitKey(0)
cv2.destroyAllWindows()


# Translation Matrix

In [13]:
tx,ty=width/2,height/2

In [14]:
Translation_matrix=np.array([[1,0,tx],[0,1,ty]])

In [15]:
Translation_matrix

array([[  1.,   0., 368.],
       [  0.,   1., 368.]])

In [16]:
Trans_im=cv2.warpAffine(src=im1,M=Translation_matrix,dsize=(width,height))

In [17]:
cv2.imshow('original image',im1)
cv2.waitKey(0)
cv2.imshow('Transimage',Trans_im)
cv2.waitKey(0)
cv2.destroyAllWindows()