# K-Means Clustering

In [6]:
import cv2 
import numpy as np

# Reading images

In [7]:
img = cv2.imread("C:/Users/SN112/Downloads/elephant.jpg")
img

array([[[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]],

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]],

       ...,

       [[230, 223, 204],
        [230, 223, 204],
        [230, 223, 204],
        ...,
        [232, 222, 204],
        [232, 222, 204],
        [232, 222, 204]],

       [[229, 222, 202],
        [229, 222, 202],
        [229, 222, 202],
        ...,
        [231, 222, 202],
        [231, 222, 202],
        [231, 222, 202]],

       [[229, 222, 202],
        [229, 222, 202],
        [229, 222, 202],
        ...,
        [231, 222, 202],
        [231, 222, 202],
        [231, 222, 202]]

# RGB Conversion








In [9]:
imgrgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

# Reshape

In [10]:
vec=imgrgb.reshape((-1,3))
vec

array([[254, 254, 254],
       [254, 254, 254],
       [254, 254, 254],
       ...,
       [202, 222, 231],
       [202, 222, 231],
       [202, 222, 231]], dtype=uint8)

# Float Conversion

In [11]:
vec = np.float32(vec)
vec


array([[254., 254., 254.],
       [254., 254., 254.],
       [254., 254., 254.],
       ...,
       [202., 222., 231.],
       [202., 222., 231.],
       [202., 222., 231.]], dtype=float32)

# Iteration Termination Criteria

In [16]:
 criteria = (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER,100,1)

# Cluster Condition

In [25]:
K=3
attempts=100

# K means Clustering

In [27]:
compactness,label,center=cv2.kmeans(vec,K,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)
center


array([[242.24628 , 245.31639 , 246.19507 ],
       [177.07571 , 181.81567 , 183.88904 ],
       [ 93.23117 ,  99.733505, 110.95207 ]], dtype=float32)

# Unit conversion

In [29]:
center=np.uint8(center)
center

array([[242, 245, 246],
       [177, 181, 183],
       [ 93,  99, 110]], dtype=uint8)

# Flattening And Reshape

In [30]:
res=center[label.flatten()]
res_img=res.reshape((imgrgb.shape))
res_img

array([[[242, 245, 246],
        [242, 245, 246],
        [242, 245, 246],
        ...,
        [242, 245, 246],
        [242, 245, 246],
        [242, 245, 246]],

       [[242, 245, 246],
        [242, 245, 246],
        [242, 245, 246],
        ...,
        [242, 245, 246],
        [242, 245, 246],
        [242, 245, 246]],

       [[242, 245, 246],
        [242, 245, 246],
        [242, 245, 246],
        ...,
        [242, 245, 246],
        [242, 245, 246],
        [242, 245, 246]],

       ...,

       [[242, 245, 246],
        [242, 245, 246],
        [242, 245, 246],
        ...,
        [242, 245, 246],
        [242, 245, 246],
        [242, 245, 246]],

       [[242, 245, 246],
        [242, 245, 246],
        [242, 245, 246],
        ...,
        [242, 245, 246],
        [242, 245, 246],
        [242, 245, 246]],

       [[242, 245, 246],
        [242, 245, 246],
        [242, 245, 246],
        ...,
        [242, 245, 246],
        [242, 245, 246],
        [242, 245, 246]]

# Orginal and Segmented Images

In [32]:
cv2.imshow('original',img)
cv2.imshow('segmented',res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()